// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import http from '@/util/http'

export function AcknowledgeAlert(arg1, arg2) {
  // return window['go']['server']['App']['AcknowledgeAlert'](arg1, arg2);
  return http.post(`/api/acknowledgeAlert`, {id: arg1, acknowledgedBy: arg2});
}

export function CheckPermission() {
  // return window['go']['server']['App']['CheckPermission']();
  return http.get(`/api/checkPermission`);
}

export function ClearAllAlerts() {
  // return window['go']['server']['App']['ClearAllAlerts']();
  return http.get(`/api/clearAllAlerts`);
}

export function ClearAllData() {
  // return window['go']['server']['App']['ClearAllData']();
  return http.get(`/api/clearAllData`);
}

export function ClearProcessStats() {
  // return window['go']['server']['App']['ClearProcessStats']();
  return http.get(`/api/clearProcessStats`);
}

export function CreateAlertRule(arg1) {
  // return window['go']['server']['App']['CreateAlertRule'](arg1);
  return http.postJson(`/api/createAlertRule`, arg1);
}

export function DeleteAlertLog(arg1) {
  // return window['go']['server']['App']['DeleteAlertLog'](arg1);
  return http.post(`/api/deleteAlertLog`, {id:arg1});
}

export function DeleteAlertRule(arg1) {
  // return window['go']['server']['App']['DeleteAlertRule'](arg1);
  return http.post(`/api/deleteAlertRule`, {id:arg1});
}

export function ExportPCAP(arg1, arg2) {
  //return window['go']['server']['App']['ExportPCAP'](arg1, arg2);
  return http.post(`/api/exportPCAP`, {startTime:arg1, endTime: arg2});
}

export function GetAlertRule(arg1) {
  // return window['go']['server']['App']['GetAlertRule'](arg1);
  return http.get(`/api/getAlertRule`, {id: arg1});
}

export function GetAlertStats() {
  // return window['go']['server']['App']['GetAlertStats']();
  return http.get(`/api/getAlertStats`);
}

export function GetConfig() {
  // return window['go']['server']['App']['GetConfig']();
  return http.get(`/api/getConfig`);
}

export function GetCurrentInterface() {
  // return window['go']['server']['App']['GetCurrentInterface']();
  return http.get(`/api/getCurrentInterface`);
}

export function GetDashboardStats() {
  // return window['go']['server']['App']['GetDashboardStats']();
   return http.get(`/api/getDashboardStats`);
}

export function GetInterfaces() {
  // return window['go']['server']['App']['GetInterfaces']();
  return http.get(`/api/getInterfaces`);
}

export function GetLibraryVersion() {
  // return window['go']['server']['App']['GetLibraryVersion']();
  return http.get(`/api/getLibraryVersion`);
}

export function GetLimits() {
  // return window['go']['server']['App']['GetLimits']();
  return http.get(`/api/getLimits`);
}

export function GetMetrics() {
  // return window['go']['server']['App']['GetMetrics']();
  return http.get(`/api/getMetrics`);
}

export function GetNpcapDownloadURL() {
  // return window['go']['server']['App']['GetNpcapDownloadURL']();
  return http.get(`/api/getNpcapDownloadURL`);
}

export function GetProcessStats(arg1, arg2) {
  // return window['go']['server']['App']['GetProcessStats'](arg1, arg2);
  return http.get(`/api/getProcessStats`, {page: arg1, size: arg2});
}

export function GetProtocolDistribution() {
  // return window['go']['server']['App']['GetProtocolDistribution']();
  return http.get(`/api/getProtocolDistribution`);
}

export function GetRawPackets(arg1) {
  // return window['go']['server']['App']['GetRawPackets'](arg1);
  return http.get(`/api/getRawPackets`, {limit: arg1});
}

export function GetSessions(arg1, arg2) {
  // return window['go']['server']['App']['GetSessions'](arg1, arg2);
  return http.get(`/api/getSessions`, {table: arg1, limit : arg2});
}

export function GetSnapshot(arg1, arg2) {
  // return window['go']['server']['App']['GetSnapshot'](arg1, arg2);
  return http.get(`/api/getSnapshot`, {table: arg1, limit : arg2});
}

export function GetStorageStats() {
  // return window['go']['server']['App']['GetStorageStats']();
  return http.get(`/api/getStorageStats`);
}

export function GetTopProcessesByTraffic(arg1) {
  // return window['go']['server']['App']['GetTopProcessesByTraffic'](arg1);
  return http.get(`/api/getTopProcessesByTraffic`, {limit: arg1});
}

export function IsCapturing() {
  // return window['go']['server']['App']['IsCapturing']();
  return http.get(`/api/isCapturing`);
}

export function IsPaused() {
  // return window['go']['server']['App']['IsPaused']();
  return http.get(`/api/isPaused`);
}

export function PauseCapture() {
  // return window['go']['server']['App']['PauseCapture']();
  return http.get(`/api/pauseCapture`);
}

export function QueryAlertLogs(arg1) {
  // return window['go']['server']['App']['QueryAlertLogs'](arg1);
  return http.postJson("/api/queryAlertLogs", arg1);
}

export function QueryAlertRules(arg1) {
  // return window['go']['server']['App']['QueryAlertRules'](arg1);
  return http.postJson(`/api/queryAlertRules`, arg1);
}

export function QuerySessionFlows(arg1) {
 // return window['go']['server']['App']['QuerySessionFlows'](arg1);
  return http.postJson(`/api/querySessionFlows`, arg1);
}

export function QuerySessions(arg1) {
  // return window['go']['server']['App']['QuerySessions'](arg1);
  return http.postJson(`/api/querySessions`, arg1);
}

export function ResumeCapture() {
  // return window['go']['server']['App']['ResumeCapture']();
  return http.get(`/api/resumeCapture`);
}

export function StartCapture(arg1) {
  // return window['go']['server']['App']['StartCapture'](arg1);
  return http.post(`/api/startCapture`, {iface: arg1});
}

export function StopCapture() {
  // return window['go']['server']['App']['StopCapture']();
  return http.get(`/api/stopCapture`);
}

export function UpdateAlertRule(arg1) {
  // return window['go']['server']['App']['UpdateAlertRule'](arg1);
  return http.postJson(`/api/updateAlertRule`, arg1);
}

export function UpdateConfig(arg1) {
  // return window['go']['server']['App']['UpdateConfig'](arg1);
  return http.postJson(`/api/updateConfig`, arg1);
}

export function UpdateLimits(arg1) {
  // return window['go']['server']['App']['UpdateLimits'](arg1);
  return http.postJson(`/api/updateLimits`, arg1);
}

export function VacuumStorage() {
  // return window['go']['server']['App']['VacuumStorage']();
  return http.get(`/api/vacuumStorage`);
}
